theme: jekyll-theme-minimal
title: Workout Report
description: Monitor personal and team lifting gains
show_downloads: true
google_analytics: UA-93454824-1
website_url: https://workout-report-1276.appspot-preview.com/
