theme: jekyll-theme-minimal
title: Workout Report
description: Monitor personal and team lifting gains
show_downloads: true
google_analytics: UA-93454824-1
website_url: https://workout-report-1276.appspot-preview.com/
workout_template_url: https://docs.google.com/spreadsheets/d/1KZ05CS_PFUBTGwD9t9K8tLa4iOzCYmlVZX5U3QxAISo/edit?usp=sharing
